/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.petshouse.telas;

import br.com.petshouse.dal.ModConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.*;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author POSITIVO
 */
public class TelaPrincipal extends javax.swing.JFrame {
  Connection  conexao = null;
                
    public TelaPrincipal() {
        initComponents();
        conexao = ModConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        menCadProdu = new javax.swing.JMenuItem();
        menCadAni = new javax.swing.JMenuItem();
        menCadUser = new javax.swing.JMenuItem();
        menCadOs = new javax.swing.JMenuItem();
        menuCadCompra = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menRel = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menRelOs = new javax.swing.JMenuItem();
        menRelFazcom = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menOpSair = new javax.swing.JMenuItem();
        menAjud = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuAjudSob = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petshouse >> Tela Principal");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1160, 750));
        setMinimumSize(new java.awt.Dimension(1200, 850));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        desktop.setBackground(new java.awt.Color(0, 204, 204));
        desktop.setPreferredSize(new java.awt.Dimension(690, 460));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 1050, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/petshouse/iconi/cachorro.png.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1070, 210, 264, 269);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(1080, 110, 260, 20);

        lblData.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblData.setText("Data");
        getContentPane().add(lblData);
        lblData.setBounds(1080, 170, 264, 20);

        menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menCad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menCad.setText("Cadastros");
        menCad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadActionPerformed(evt);
            }
        });

        menCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadCli.setText("Cliente");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        menCad.add(menCadCli);

        menCadProdu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadProdu.setText("Produtos");
        menCadProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadProduActionPerformed(evt);
            }
        });
        menCad.add(menCadProdu);

        menCadAni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadAni.setText("Animal");
        menCadAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAniActionPerformed(evt);
            }
        });
        menCad.add(menCadAni);

        menCadUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadUser.setText("Usuarios");
        menCadUser.setEnabled(false);
        menCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUserActionPerformed(evt);
            }
        });
        menCad.add(menCadUser);

        menCadOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadOs.setText("OS");
        menCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadOsActionPerformed(evt);
            }
        });
        menCad.add(menCadOs);

        menuCadCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCadCompra.setText("Compra");
        menuCadCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCompraActionPerformed(evt);
            }
        });
        menCad.add(menuCadCompra);
        menCad.add(jSeparator1);

        menu.add(menCad);

        menRel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menRel.setText("Relatórios");
        menRel.setEnabled(false);
        menRel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menRel.add(jSeparator2);

        menRelOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelOs.setText("Ordem de serviços");
        menRelOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelOsActionPerformed(evt);
            }
        });
        menRel.add(menRelOs);

        menRelFazcom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelFazcom.setText("Faz/compra");
        menRelFazcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelFazcomActionPerformed(evt);
            }
        });
        menRel.add(menRelFazcom);

        menu.add(menRel);

        menOpc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menOpc.setText("Opções");
        menOpc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menOpc.add(jSeparator3);

        menOpSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpSair.setText("Sair");
        menOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpSairActionPerformed(evt);
            }
        });
        menOpc.add(menOpSair);

        menu.add(menOpc);

        menAjud.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menAjud.setText("Ajuda");
        menAjud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menAjud.add(jSeparator4);

        menuAjudSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuAjudSob.setText("Sobre");
        menuAjudSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudSobActionPerformed(evt);
            }
        });
        menAjud.add(menuAjudSob);

        menu.add(menAjud);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(1448, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substitui a label pela data e hora atual do sistema
       // ao inicializar o forme
       Date data = new Date();
       DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
       lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void menOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpSairActionPerformed
        // exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if ( sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_menOpSairActionPerformed

    private void menuAjudSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudSobActionPerformed
        // chamando a tela sobre
        TelaSobre Sobre = new TelaSobre();
        Sobre.setVisible(true);
    }//GEN-LAST:event_menuAjudSobActionPerformed

    private void menCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadActionPerformed
       //evento nulo
    }//GEN-LAST:event_menCadActionPerformed

    private void menCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUserActionPerformed
        // as linhas abaixo vai abrir o form tela usuario dentro do descktop
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_menCadUserActionPerformed

    private void menCadProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadProduActionPerformed
        //as linhas abaixo abre o form de cadadstro de produto
        TelaProduto produto = new TelaProduto();
        produto.setVisible(true);
        desktop.add(produto);
        
    }//GEN-LAST:event_menCadProduActionPerformed

    private void menuCadCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCompraActionPerformed
        // as linhas abaixo abre o form de cadastro de compras
        TelaCompra compra = new TelaCompra();
        compra.setVisible(true);
        desktop.add(compra);
    }//GEN-LAST:event_menuCadCompraActionPerformed

    private void menCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadOsActionPerformed
        // as linhas abaixo abre o form de ordem de serviços;
        TelaOs os = new TelaOs();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_menCadOsActionPerformed

    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        // as linhas abaixo abre o form de cadastro de cliente;
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_menCadCliActionPerformed

    private void menCadAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAniActionPerformed
        //  as linhas abaixo abre o form de cadastro de animais
        TelaAnimal animal = new TelaAnimal();
        animal.setVisible(true);
        desktop.add(animal);
    }//GEN-LAST:event_menCadAniActionPerformed

    private void menRelFazcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelFazcomActionPerformed
        // gera um grelatorio de compras
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatorio?","Atenção",JOptionPane.YES_NO_OPTION);
       if (confirma == JOptionPane.YES_OPTION){
        //imprimindo o relatorio com o framework jasperReport   
           try {
             // usando a classe jasper Print para preparar a impressao de um relatorio
          JasperPrint print = JasperFillManager.fillReport("C:/Reports/compras.jasper",null,conexao);
         // alinha abaixo exibe o relatorio atraves da calasse JasperViewer
         JasperViewer.viewReport(print, false);
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }
    }//GEN-LAST:event_menRelFazcomActionPerformed

    private void menRelOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelOsActionPerformed
             // gera um grelatorio de ordem de servicos
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatorio?","Atenção",JOptionPane.YES_NO_OPTION);
       if (confirma == JOptionPane.YES_OPTION){
        //imprimindo o relatorio com o framework jasperReport   
           try {
             // usando a classe jasper Print para preparar a impressao de um relatorio
          JasperPrint print = JasperFillManager.fillReport("C:/Reports/Relatorio_OS.jasper",null,conexao);
         // alinha abaixo exibe o relatorio atraves da calasse JasperViewer
         JasperViewer.viewReport(print, false);
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }
    }//GEN-LAST:event_menRelOsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menAjud;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadAni;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenuItem menCadOs;
    private javax.swing.JMenuItem menCadProdu;
    public static javax.swing.JMenuItem menCadUser;
    private javax.swing.JMenuItem menOpSair;
    private javax.swing.JMenu menOpc;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelFazcom;
    private javax.swing.JMenuItem menRelOs;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAjudSob;
    private javax.swing.JMenuItem menuCadCompra;
    // End of variables declaration//GEN-END:variables
}
